HW10 is completed
Antonov-Alexander/otus-go pull request #10
Opened 2023-01-13 20:41 UTC by Antonov-Alexander

## Домашнее задание №10 «Оптимизация программы»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я написал бенчмарк и приложил результаты benchstat.

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2023-01-14 19:31 UTC, Antonov-Alexander commented
TestGetDomainStat_Time_And_Memory
*Old*
```
    stats_optimization_test.go:45: time used: 573.152001ms / 300ms
    stats_optimization_test.go:46: memory used: 307Mb / 30Mb
```

*New*
```
    stats_optimization_test.go:46: time used: 146.677154ms / 300ms
    stats_optimization_test.go:47: memory used: 4Mb / 30Mb
```

2023-01-14 21:43 UTC, gna69 requested changes
Отлично, что в работе используется fastjson для анмаршалинга. Алгоритм подсчета доменов построек верно.

Текущий код не использует структуру User. Следует обратить внимание на то, что в реальном проекте вся бизнес логика скорее всего была бы построена вокруг этого объекта и просто так избавиться от него врятли бы получилось.

В рамках текущей задачи - это отличная оптимизация, избавление от лишней логики и анмаршаллинг только поля Email.

2023-01-14 21:43 UTC, gna69 commented on hw10_program_optimization/stats.go
> +			if char == 64 {
Предлагаю вынести значение 64 (как и значение 46 на строке 39) в константу и использовать ее. Это повысит читаемость и ясность кода.
Еще можно изменить немного логику программы и уменьшить вложенность кода: if код символа не 64 => continue. А после такого if логику проверки домена. Чем меньше вложенность кода, тем проще его читать

2023-01-14 21:43 UTC, gna69 commented on hw10_program_optimization/stats.go
> +				for domainPos, domainChar := range emailDomain {
Чтобы не перебирать каждый символ, можно воспользоваться strings.Contains для поиска в строке нужного символа, и при его наличии воспользоваться strings.Split для получения домена
Этими же функциями можно воспользоваться и на строке 34, возможно получится вовсе избавиться от циклов и код сильно упростится

2023-01-14 21:43 UTC, gna69 commented on hw10_program_optimization/stats_test.go
> +	t.Run("Only emails json", func(t *testing.T) {
Тест "Only emails json" копирует функционал теста "find 'com'", отличаются они только входными данными. Предлагаю добавить тестов для тех ситуаций, которые еще не проверены. Например, парсинг не валидного json и негативные кейсы с неправильным email.

2023-01-14 21:43 UTC, gna69 commented on hw10_program_optimization/stats.go
> +			return result, err
При возникновении ошибки в го сообществе принято возвращать значения по умолчанию и ошибку. При игнорировании ошибки в вызываемом коде (чего тоже нельзя делать) в данном случае вернется объект и поиск ошибки почему этот объект пустой может занять значительное количество времени.

2023-01-16 18:57 UTC, Antonov-Alexander commented on hw10_program_optimization/stats.go
> +			if char == 64 {
Согласен. Сейчас и не вспомнил, что за символы 64 и 46
Сделал без char, по совету из коммента ниже

2023-01-16 18:58 UTC, Antonov-Alexander commented on hw10_program_optimization/stats.go
> +				for domainPos, domainChar := range emailDomain {
Сделал через strings.Split

2023-01-16 19:00 UTC, Antonov-Alexander commented on hw10_program_optimization/stats.go
> +			return result, err
Ок, спс. Добавил возвращение ошибки `no matched email domains`, если ничего не нашлось

2023-01-16 19:09 UTC, Antonov-Alexander commented on hw10_program_optimization/stats.go
> +			return result, err
Убрал обратно, потому что есть тест `find 'unknown'`, который на выходе хочет пустой объект `DomainStat{}` и чтоб не было ошибок

2023-01-16 19:11 UTC, Antonov-Alexander commented on hw10_program_optimization/stats_test.go
> +	t.Run("Only emails json", func(t *testing.T) {
Этот тест оставил, в нём проверял json, который имеет не все поля, по сравнению с остальными
+ добавил 2 теста:
- невалидный json - выдаётся ошибка
- неправильный email - пропускается

2023-01-16 20:07 UTC, gna69 approved these changes
Отлично! Код стал проще, короче, более читабельный. Тесты покрывают как позитивные, так и негативные кейсы. Задача выполнена.

2023-01-17 07:23 UTC, merged