HW8 is completed
Antonov-Alexander/otus-go pull request #8
Opened 2023-01-10 19:03 UTC by Antonov-Alexander

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-01-11 11:03 UTC, dshemin requested changes

2023-01-11 11:03 UTC, dshemin commented on hw08_envdir_tool/env_reader.go
> +		file, err := os.Open(dir + "/" + dirFile.Name())
Критично:

Обратите внимание на задание:
> имя `S` не должно содержать `=`

2023-01-11 11:03 UTC, dshemin commented on hw08_envdir_tool/env_reader.go
> +		result[dirFile.Name()] = EnvValue{value, value == ""}
Важно:

Не используйте такой способ инициализации структур. Такая инициализация сломается если поменять порядок полей в EnvValue.

2023-01-11 11:03 UTC, dshemin commented on hw08_envdir_tool/env_reader_test.go
> +	_ = os.Mkdir(testParams.dir, 0o755)
Важно:

Не стоит игнорировать ошибки в тесте. Может привести к неожиданным ошибкам. Используйте `require.NoError` из пакета testify

2023-01-11 11:03 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +	stdout, stderr := new(strings.Builder), new(strings.Builder)
Важно:

А зачем нам тут использовать буфер если мы можем просто передать os.Stdout и os.Stderr чтобы сразу выводить ответ команды в поток вывода и ошибок без аккумуляции в памяти?

2023-01-11 11:03 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +		return 1
Критично:

Обратите внимание на задание:

> код выхода утилиты совпадал с кодом выхода программы.

2023-01-11 11:03 UTC, dshemin commented on hw08_envdir_tool/main.go
> +	RunCmd(os.Args[2:], env)
Критично:

Код ошибки не возвращается. Нет os.Exit.

2023-01-11 19:43 UTC, Antonov-Alexander commented on hw08_envdir_tool/env_reader.go
> +		file, err := os.Open(dir + "/" + dirFile.Name())
Точно. Учёл и добавил тест

2023-01-11 19:43 UTC, Antonov-Alexander commented on hw08_envdir_tool/env_reader.go
> +		result[dirFile.Name()] = EnvValue{value, value == ""}
Понял. Спасибо
Поменял

2023-01-11 19:43 UTC, Antonov-Alexander commented on hw08_envdir_tool/env_reader_test.go
> +	_ = os.Mkdir(testParams.dir, 0o755)
Мм. Сделал, спасибо

2023-01-11 19:45 UTC, Antonov-Alexander commented on hw08_envdir_tool/executor.go
> +	stdout, stderr := new(strings.Builder), new(strings.Builder)
Думал, что раз через нашу программу проходит вызов, то и буфер надо тоже нужен.
Сделал
```
executor.Stdout = os.Stdout
executor.Stderr = os.Stderr
````

2023-01-11 19:46 UTC, Antonov-Alexander commented on hw08_envdir_tool/executor.go
> +		return 1
Не знаю правильно ли, но поменял на `var exitErr *exec.ExitError` -> `return exitErr.ExitCode()`

2023-01-11 19:47 UTC, Antonov-Alexander commented on hw08_envdir_tool/main.go
> +	RunCmd(os.Args[2:], env)
🙊
Добавил

2023-01-11 22:00 UTC, dshemin requested changes

2023-01-11 22:00 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +	executor.Stdout = os.Stdout
Критично:

Совсем забыл, в задании сказано что и поток ввода тоже надо перенаправить.

2023-01-12 07:38 UTC, Antonov-Alexander commented on hw08_envdir_tool/executor.go
> +	executor.Stdout = os.Stdout
А достаточно сделать так `executor.Stdin = os.Stdin` ?

2023-01-17 18:45 UTC, merged