HW9 is completed
Antonov-Alexander/otus-go pull request #9
Opened 2023-01-12 21:33 UTC by Antonov-Alexander

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2023-01-13 03:43 UTC, dshemin requested changes

2023-01-13 03:43 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	objectFields := reflect.VisibleFields(reflect.TypeOf(v))
Критично:

Нет проверки на то, что `v` - это структура.

2023-01-13 03:43 UTC, dshemin commented on hw09_struct_validator/validator.go
> +			return fmt.Errorf("validator parsing error (%s)", validateValue)
Важно:

Слишком общая ошибка, как пользователю понять что именно он сделал не так?

2023-01-13 03:43 UTC, dshemin commented on hw09_struct_validator/validator.go
> +				return fmt.Errorf("validator parsing error (%s)", validation)
Важно:

Слишком общая ошибка, как пользователю понять что именно он сделал не так?

2023-01-13 03:43 UTC, dshemin commented on hw09_struct_validator/validator.go
> +					Err:   fmt.Errorf("validation failed on '%s'", validation),
Важно:

Если на поле будет несколько валиадаторов то мы получим общую ошибку из которой пользователю будет непонятно какой именно констрейнт был нарушен. Представьте что вы отправляете запрос на сервер, а вам вернут ответ - `validation failed`. Как понять что именно не так?

2023-01-13 03:43 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	var re *regexp.Regexp
Важно:

Определение переменной должно быть как можно ближе к месту где она реально используется. Более того, она даже не в этом блоке кода используется.

2023-01-13 07:36 UTC, Antonov-Alexander commented on hw09_struct_validator/validator.go
> +	var re *regexp.Regexp
это же кэш, чтобы не компилить одну и ту же регулярку каждый раз в цикле

2023-01-13 07:36 UTC, Antonov-Alexander commented on hw09_struct_validator/validator.go
> +				return fmt.Errorf("validator parsing error (%s)", validation)
в ошибке же будет написано название поля и какой именно валидатор оно не прошло

2023-01-13 07:36 UTC, Antonov-Alexander commented on hw09_struct_validator/validator.go
> +					Err:   fmt.Errorf("validation failed on '%s'", validation),
Нет, пользователю потом для каждого поля соберутся все валидаторы, которые он не пришёл (выше код `return strings.Join(result, ", ")`)

Пример итоговой ошибки выглядит так
```
invalid Age: validation failed on 'min:18', invalid Email: validation failed on 'regexp:^\w+@\w+\.\w+$', invalid Phones: validation failed on 'len:11'
```

2023-01-13 07:36 UTC, Antonov-Alexander commented on hw09_struct_validator/validator.go
> +			return fmt.Errorf("validator parsing error (%s)", validateValue)
Ниже отписался
Итоговая ошибка выглядит так
```
validation failed on 'regexp:^\w+@\w+\.\w+$', invalid Phones: validation failed on 'len:11'
```

2023-01-13 19:02 UTC, Antonov-Alexander commented on hw09_struct_validator/validator.go
> +	objectFields := reflect.VisibleFields(reflect.TypeOf(v))
добавил

2023-01-14 07:49 UTC, dshemin approved these changes

2023-01-14 07:49 UTC, dshemin commented on hw09_struct_validator/validator.go
> +			return fmt.Errorf("validator parsing error (%s)", validateValue)
Тут мы возвращает ошибку если у нас нет валидаторов для поля, точнее при разборе строки мы их не нашли. Как ему догадаться что он указал пустую строку?

2023-01-14 07:49 UTC, dshemin commented on hw09_struct_validator/validator.go
> +				return fmt.Errorf("validator parsing error (%s)", validation)
А мы тут ещё не дошли до валидации, мы тут только разбираем строку, которую мы получили от пользователя нашей библиотеки.  Как ему догадаться что он забыл `:` поставить? Или где-то он лишнюю поставил.

2023-01-14 07:49 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	var re *regexp.Regexp
Увидел.

2023-01-14 07:49 UTC, dshemin commented on hw09_struct_validator/validator.go
> +					Err:   fmt.Errorf("validation failed on '%s'", validation),
Окей, для ДЗ пойдёт, но обратите внимание как сообщения об ошибках пишут уже существующие валидаторы.

2023-01-14 19:18 UTC, Antonov-Alexander commented on hw09_struct_validator/validator.go
> +					Err:   fmt.Errorf("validation failed on '%s'", validation),
Ок

2023-01-17 18:43 UTC, merged